"""Tunable runtime configuration for the OpenMV H7 Plus D-task detector."""

DETECTOR_BACKEND = 'fast_v2'
IMAGE_WIDTH, IMAGE_HEIGHT = 320, 240

MIN_CONFIDENCE = 55
CONFIRM_FRAMES = 3
TARGET_RATIO_NOMINAL = 0.60

SEARCH_FULL_VERIFY_INTERVAL = 8
TRACK_FULL_VERIFY_INTERVAL = 12
MAX_CANDIDATE_REGIONS = 2
MAX_STRONG_VERIFY_AGE = 12
MAX_CONSECUTIVE_VERIFY_FAILURES = 4
ROI_SCALE = 1.65
ROI_SCALE_PERCENT = 165
ROI_EXPAND_STEP = 1.35
ROI_MAX_LOST_FRAMES = 3
ROI_FAILURE_LIMIT = 3
FULL_SEARCH_INTERVAL = 8
MAX_TRACK_JUMP_DIAMETER_RATIO = 1.35
MIN_TRACK_SIZE_RATIO = 0.70
MAX_TRACK_SIZE_RATIO = 1.45

MIN_OUTER_DIAMETER = 24
MAX_OUTER_DIAMETER = 220
MIN_CIRCLE_DIAMETER = 10
INNER_OUTER_RATIO_MIN = 0.52
INNER_OUTER_RATIO_MAX = 0.68
MAX_CONCENTRIC_ERROR = 0.10

MIN_BLOB_PIXELS = 30
MIN_BLOB_AREA = 80
MIN_BLOB_ASPECT = 0.55
MIN_BLOB_ROUNDNESS = 0.10
BLOB_MERGE = False
ENABLE_MERGED_BLOB_FALLBACK = True
BLOB_MARGIN_PIXELS = 8
BLOB_MARGIN_DIVISOR = 4
BLOB_MERGED_MARGIN = 4
MAX_SEARCH_REGIONS = 4

CIRCLE_THRESHOLD = 1400
CIRCLE_X_STRIDE = 2
CIRCLE_Y_STRIDE = 2
CIRCLE_X_MARGIN = 6
CIRCLE_Y_MARGIN = 6
CIRCLE_R_MARGIN = 6
CIRCLE_R_MIN = 6
CIRCLE_R_STEP = 2
MIN_CIRCLE_SCORE = 0.35
OUTER_RADIUS_TOLERANCE_RATIO = 0.22
INNER_RADIUS_TOLERANCE_RATIO = 0.22

CROSS_ROI_RADIUS_RATIO = 0.62
LINE_X_STRIDE = 2
LINE_Y_STRIDE = 1
LINE_THRESHOLD = 550
LINE_THETA_MARGIN = 8
LINE_RHO_MARGIN = 8
MIN_LINE_LENGTH_RATIO = 0.35
LINE_CENTER_DISTANCE_MIN = 4.0
LINE_CENTER_DISTANCE_RATIO = 0.18
CROSS_ANGLE_TOLERANCE_DEG = 22
CROSS_LINE_SUM_RATIO = 1.00
CROSS_DISTANCE_PENALTY_RATIO = 0.28
MIN_CROSS_SCORE = 0.45

OUTPUT_PERIOD_MS = 0
TIMING_ENABLED = True
PROTOCOL_TRANSPORT = 'stdout'
USB_VCP_ID = 0
DEBUG_DRAW = False

DIAGNOSTIC_PERIOD_MS = 1000
CONFIG_REPEAT_PERIOD_MS = 10000
DEBUG_CAPTURE_ONCE = False
DEBUG_CAPTURE_RAW_PATH = '/flash/debug_raw.pgm'
DEBUG_CAPTURE_THRESHOLD_PATH = '/flash/debug_threshold.pgm'

CONFIG_EXPORT_KEYS = (
    'DETECTOR_BACKEND', 'IMAGE_WIDTH', 'IMAGE_HEIGHT', 'MIN_CONFIDENCE',
    'SEARCH_FULL_VERIFY_INTERVAL', 'TRACK_FULL_VERIFY_INTERVAL',
    'MAX_CANDIDATE_REGIONS', 'MAX_STRONG_VERIFY_AGE',
    'MAX_CONSECUTIVE_VERIFY_FAILURES', 'ROI_SCALE',
    'ROI_SCALE_PERCENT', 'ROI_MAX_LOST_FRAMES', 'ROI_FAILURE_LIMIT',
    'FULL_SEARCH_INTERVAL', 'MIN_OUTER_DIAMETER', 'MAX_OUTER_DIAMETER',
    'MIN_CIRCLE_DIAMETER', 'INNER_OUTER_RATIO_MIN', 'INNER_OUTER_RATIO_MAX',
    'TARGET_RATIO_NOMINAL', 'MAX_CONCENTRIC_ERROR', 'MIN_BLOB_PIXELS',
    'MIN_BLOB_AREA', 'MIN_BLOB_ASPECT', 'MIN_BLOB_ROUNDNESS', 'BLOB_MERGE',
    'ENABLE_MERGED_BLOB_FALLBACK', 'CIRCLE_THRESHOLD', 'LINE_THRESHOLD',
    'MIN_LINE_LENGTH_RATIO', 'LINE_CENTER_DISTANCE_RATIO',
    'MIN_CROSS_SCORE', 'MAX_TRACK_JUMP_DIAMETER_RATIO',
    'MIN_TRACK_SIZE_RATIO', 'MAX_TRACK_SIZE_RATIO',
    'OUTER_RADIUS_TOLERANCE_RATIO', 'INNER_RADIUS_TOLERANCE_RATIO',
    'DIAGNOSTIC_PERIOD_MS', 'CONFIG_REPEAT_PERIOD_MS', 'DEBUG_CAPTURE_ONCE'
)


def runtime_config_snapshot():
    return {key: globals()[key] for key in CONFIG_EXPORT_KEYS}


def format_runtime_config_line():
    pairs = []
    for key, value in sorted(runtime_config_snapshot().items()):
        pairs.append('%s=%s' % (key, value))
    return 'D_CONFIG,%s\n' % ','.join(pairs)
